### PR TITLE
Section two added

### PR DESCRIPTION
**Pull request by JoshuaOyewole**
Kindly review my branch.
Have added the section and its currently responsive on both mobile and desktops.

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
You need to add a bit more margin between the button and the text. 
You also omitted the Icon in the contact us button, 
You also need to look at the mobile screen and ensure it fits the UI given
@JoshuaOyewole

**Comment by JoshuaOyewole** [comment]
I have added the icon to the contact us button

**Comment by JoshuaOyewole** [comment]
I have fixed all the bugs in this section

**Comment by PhilemonBrain** [comment]
Nice work

**Review by PhilemonBrain — APPROVED** [review]
Done

**Pull request merged**
