### PR TITLE
Section four

### PR DESCRIPTION
**Pull request by JoshuaOyewole**
Kindly review this section.

**Challenges facing in this section**
- I am currently having issues centralizing the content on mobile view as all the grid Items are still aligning to the left instead of the center as shown in the mockup.
- In normal CSS, I could just do a:
`@media (max-width:600px){
    elem{display: flex; justify-content: center; align-items: center}
`
I want to replicate this in MateralUI also.

Below is a visual representation of what am saying
origin-design
mine-error

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
@JoshuaOyewole
On section 2
  You need to add a bit more margin between the button and the text.
  You also omitted the Icon in the contact us button,
  You also need to look at the mobile screen and ensure it fits the UI given

**Comment by PhilemonBrain** [comment]
I have fixed all the issues on section four

**Comment by JoshuaOyewole** [comment]
> @JoshuaOyewole On section 2 You need to add a bit more margin between the button and the text. You also omitted the Icon in the contact us button, You also need to look at the mobile screen and ensure it fits the UI given

okay, I have added the icon in the contact us button

**Comment by PhilemonBrain** [comment]
I mentioned 3 things, have you fixed them all?

**Comment by JoshuaOyewole** [comment]
Yes.
I have fixed all three

**Comment by JoshuaOyewole** [comment]
@PhilemonBrain can you merge the PR for this sectionFour.
Since the remaining bugs have been fixed by you

**Pull request closed without merging**
